// Generated by LiveScript 1.4.0
(function(){
  var express, url;
  express = require('express');
  url = require('url');
  module.exports = {
    start: function(port, path){
      var app, server;
      port == null && (port = 3025);
      path == null && (path = "/dy2");
      app = express();
      app.get(path + "/load/:document", function(req, res){
        var document, createRepoFromDocument;
        document = req.params.document;
        createRepoFromDocument = require('./doc-loader').createRepoFromDocument;
        return createRepoFromDocument(document, function(repo){
          var rawRepo;
          rawRepo = repo.exportRepo();
          return res.send(JSON.stringify(rawRepo) + "\n");
        });
      });
      return server = app.listen(port, function(){
        var host, port;
        host = server.address().address;
        port = server.address().port;
        return console.log('Listening on http://%s:%s', host, port);
      });
    }
  };
  if (process.argv[0] === 'node' && process.argv[1] === __filename) {
    module.exports.start();
  }
}).call(this);
